export const doctorFormData = [
    { name: "firstName", label: "First Name", placeholder: "Enter First Name", type: "text" },
    { name: "lastName", label: "Last Name", placeholder: "Enter Last Name", type: "text" },
    { name: "dateOfBirth", label: "Date of Birth", placeholder: "Enter Date of Birth", type: "date" },
    { name: "gender", label: "Gender", placeholder: "Enter Gender", type: "text" },
    { name: "phoneNumber", label: "Phone Number", placeholder: "Enter Phone Number", type: "text" },
    { name: "email", label: "Email", placeholder: "Enter Email", type: "email" },
    { name: "address", label: "Address", placeholder: "Enter Address", type: "text" },
    { name: "profilePicture", label: "Profile Picture", placeholder: "Enter Profile Picture URL", type: "text" },
    { name: "medicalLicenseNumber", label: "Medical License Number", placeholder: "Enter Medical License Number", type: "text" },
    { name: "specialty", label: "Specialty", placeholder: "Enter Specialty", type: "text" },
    { name: "yearsOfExperience", label: "Years of Experience", placeholder: "Enter Years of Experience", type: "number" },
    { name: "currentPracticeLocation", label: "Current Practice Location", placeholder: "Enter Current Practice Location", type: "text" },
    { name: "professionalAffiliations", label: "Professional Affiliations", placeholder: "Enter Professional Affiliations", type: "text" },
    { name: "languagesSpoken", label: "Languages Spoken", placeholder: "Enter Languages Spoken", type: "text" },
    { name: "medicalSchool", label: "Medical School", placeholder: "Enter Medical School", type: "text" },
    { name: "graduationYear", label: "Graduation Year", placeholder: "Enter Graduation Year", type: "number" },
    { name: "residencyPrograms", label: "Residency Programs", placeholder: "Enter Residency Programs", type: "text" },
    { name: "fellowships", label: "Fellowships", placeholder: "Enter Fellowships", type: "text" },
    { name: "certifications", label: "Certifications", placeholder: "Enter Certifications", type: "text" },
    { name: "previousEmployment", label: "Previous Employment", placeholder: "Enter Previous Employment", type: "text" },
    { name: "currentEmployment", label: "Current Employment", placeholder: "Enter Current Employment", type: "text"},
]
  