import { z } from 'zod';

export const doctorFormSchema = z.object({
  firstName: z.string().min(1, 'First Name is required'),
  lastName: z.string().min(1, 'Last Name is required'),
  dateOfBirth: z.string().min(1, 'Date of Birth is required'),
  gender: z.string().min(1, 'Gender is required'),
  phoneNumber: z.string().regex(/^\d{12}$/, 'Phone number must be exactly 12 digits'),
  address: z.string().min(1, 'Address is required'),
  city: z.string().min(1, 'city is required'),
  profilePicture: z.string().url('Invalid URL'),
  medicalLicenseNumber: z.string().min(1, 'Medical License Number is required'),
  specialty: z.string().min(1, 'Specialty is required'),
  yearsOfExperience: z.string().min(0, 'Years of Experience is required'),
  currentPracticeLocation: z.string().min(1, 'Current Practice Location is required'),
  professionalAffiliations: z.string().min(1, 'Professional Affiliations are required'),
  languagesSpoken: z.string().min(1, 'Languages Spoken are required'),
  medicalSchool: z.string().min(1, 'Medical School is required'),
  graduationYear: z.string().min(1, 'Graduation Year is required'),
  residencyPrograms: z.string().min(1, 'Residency Programs are required'),
  fellowships: z.string().min(1, 'Fellowships are required'),
  certifications: z.string().min(1, 'Certifications are required'),
  previousEmployment: z.string().min(1, 'Previous Employment is required'),
  currentEmployment: z.string().min(1, 'Current Employment is required'),
  checkUpFee: z.string().min(1, 'Current Employment is required'),
  healthConditions: z.string().optional(),
  previousSurgeries: z.string().optional(),
  allergies: z.string().optional(),
  medications: z.string().optional(),
  references: z.string().optional(),
  publications: z.string().optional(),
  statementOfPurpose: z.string().optional(),
  consent: z.boolean().refine(value => value === true, { message: 'You must consent to the terms' }),
});
